### ISSUE TITLE
JSON file missing.

### ISSUE THREAD

**Issue by aravind1705** [vongohren/rahman-contracts#1]
ERROR in ./app/javascripts/app.js
Module not found: Error: Can't resolve '../../build/contracts/CourseHub.json' in '../../app/javascripts'
 @ ./app/javascripts/app.js 3:0-70

ERROR in ./app/javascripts/app.js
Module not found: Error: Can't resolve '../../build/contracts/Course.json' in '../../app/javascripts'
 @ ./app/javascripts/app.js 4:0-64

Please provide JSON File.

**Comment by vongohren** [comment]
@aravind1705 you have to build those youself through truffle

**Comment by aravind1705** [comment]
Got it.

**Comment by aravind1705** [comment]
Can you please help me running this project? I compiled the code using truffle. Built using this command 
`npm run-script build`  and I'm running it through `npm run-script dev`. Am I doing it right?

**Comment by vongohren** [comment]
what you need to do is just to run npm install. Then truffle test.
The npm scripts are not up to date, because its not really a very finished product.
Are you friends with rahman since you found this repo?
